import { Metadata } from 'next';
import { BulletList, LegalPage } from '@/components/legal/LegalPage';

export const metadata: Metadata = {
  title: 'Privacy Notice | NLF 2026 Vendor Portal',
  description: 'How the National Livestock Festival Vendor Portal handles personal information.',
};

export default function PrivacyPage() {
  return <LegalPage
    eyebrow="Privacy"
    title="Privacy Notice"
    intro={<>This notice explains how the National Livestock Festival 2026 Vendor Portal collects, uses, and shares information when you browse the Portal, create an account, apply for exhibition space, or contact the Secretariat. We handle personal data under applicable Nigerian data-protection law, including the Nigeria Data Protection Act 2023.</>}
    sections={[
      { title: 'Who is responsible for your information', content: <p>The National Livestock Festival Secretariat administers exhibitor applications through this Portal and is responsible for the event-related information described here. For privacy questions or requests, email <a className="font-semibold text-[#1E4D38] hover:underline" href="mailto:exhibit@carnival.ng">exhibit@carnival.ng</a> with “Privacy request” in the subject. The event’s full legal contracting entity and postal address are not identified in the Portal; please request them from the Secretariat if you need formal service details.</p> },
      { title: 'Information we collect', content: <BulletList><li><strong>Account details:</strong> name or organization name, email address, and authentication details managed through Supabase Auth or Google sign-in.</li><li><strong>Vendor and application details:</strong> organization, contact person, phone number, business sector, website, business description, booth tier, custom requests, reservation status, allocation, and application history.</li><li><strong>Payment records:</strong> amount, currency, payment status, and transaction reference needed to verify and reconcile a booth payment. Payment card and bank credentials are handled by Paystack; they are not stored by this Portal.</li><li><strong>Technical and security data:</strong> information that our hosting, authentication, database, and payment services generate to provide, protect, and troubleshoot their services. This can include log and device information.</li><li><strong>Messages:</strong> information you choose to provide when you contact the Secretariat.</li></BulletList> },
      { title: 'Why we use it and our grounds', content: <BulletList><li>To create and secure accounts, authenticate users, administer applications, allocate booths, issue permits, and provide event services you request (steps toward or performance of an agreement).</li><li>To take and reconcile payments, prevent fraud, keep accounting records, and comply with legal obligations (legal obligation and legitimate interests, as applicable).</li><li>To operate, maintain, and secure the Portal, investigate misuse, and respond to support requests (legitimate interests, balanced against your rights).</li><li>Where required, to send optional communications based on your consent. You can withdraw consent by contacting us.</li></BulletList> },
      { title: 'Who receives information', content: <p>Information is shared only as needed with event Secretariat staff who administer applications and with service providers that support the Portal: Supabase (authentication and database), Hostinger (website hosting), Paystack (payment processing and verification), and Google when you choose Google sign-in. These providers process information under their own terms and privacy notices. We may also disclose information where required by law, to address security or fraud, or to protect users and the event. We do not sell your personal information.</p> },
      { title: 'International processing and safeguards', content: <p>Some service providers or their infrastructure may process information outside Nigeria. Where this occurs, the Secretariat should use safeguards required by applicable data-protection law and the provider’s contractual protections. Contact us if you would like more information about relevant safeguards.</p> },
      { title: 'Retention', content: <p>We keep account and application information for as long as needed to administer the event, provide permits and support, maintain business and payment records, resolve disputes, and meet legal obligations. Retention periods depend on the record and applicable requirements. Information that is no longer needed should be securely deleted or de-identified, subject to lawful retention requirements.</p> },
      { title: 'Your choices and rights', content: <><p>Subject to applicable law and verification of your identity, you may ask us to:</p><BulletList><li>confirm whether we process your personal data and provide access to it;</li><li>correct inaccurate or incomplete information;</li><li>delete information or restrict or object to certain processing;</li><li>receive information you provided in a portable format, where applicable;</li><li>withdraw consent where processing relies on consent; or</li><li>raise a concern with the Nigeria Data Protection Commission.</li></BulletList><p>Some records may need to be retained to provide event services, prevent fraud, or meet legal obligations. Send requests to <a className="font-semibold text-[#1E4D38] hover:underline" href="mailto:exhibit@carnival.ng">exhibit@carnival.ng</a>.</p></> },
      { title: 'Security and children', content: <p>We use reasonable administrative and technical measures to protect information, but no internet service can guarantee absolute security. The Portal is intended for business exhibitors and is not designed for children. Please do not submit children’s personal data unless it is necessary for an event purpose and you are authorized to provide it.</p> },
      { title: 'Updates and complaints', content: <p>We may update this notice as the Portal or event practices change. The revision date appears above. Contact the Secretariat first with privacy questions or concerns. You may also contact the Nigeria Data Protection Commission through its official website at <a className="font-semibold text-[#1E4D38] hover:underline" href="https://ndpc.gov.ng/" target="_blank" rel="noreferrer">ndpc.gov.ng</a>.</p> },
    ]}
  />;
}
